<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32539" started-at="2019-12-06T16:19:45 IST" finished-at="2019-12-06T16:20:17 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32539" started-at="2019-12-06T16:19:45 IST" finished-at="2019-12-06T16:20:17 IST">
      <class name="com.training.High.tests.TC01_InvalidDatailsAddingProduct">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.High.tests.TC01_InvalidDatailsAddingProduct@57855c9a]" name="setUpBeforeClass" is-config="true" duration-ms="47" started-at="2019-12-06T16:19:45 IST" finished-at="2019-12-06T16:19:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="FAIL" signature="addaproductusinginvaliddetails(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.High.tests.TC01_InvalidDatailsAddingProduct@57855c9a]" name="addaproductusinginvaliddetails" duration-ms="0" started-at="2019-12-06T16:19:45 IST" data-provider="getData" finished-at="2019-12-06T16:19:45 IST">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.training.High.tests.TC01_InvalidDatailsAddingProduct.addaproductusinginvaliddetails(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : getData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.training.High.tests.TC01_InvalidDatailsAddingProduct.addaproductusinginvaliddetails(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : getData
at org.testng.internal.Parameters.findDataProvider(Parameters.java:580)
at org.testng.internal.Parameters.handleParameters(Parameters.java:795)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addaproductusinginvaliddetails -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.High.tests.TC01_InvalidDatailsAddingProduct@57855c9a]" name="setUp" is-config="true" duration-ms="18940" started-at="2019-12-06T16:19:45 IST" finished-at="2019-12-06T16:20:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="catalogLoginTest()[pri:1, instance:com.training.High.tests.TC01_InvalidDatailsAddingProduct@57855c9a]" name="catalogLoginTest" duration-ms="12259" started-at="2019-12-06T16:20:04 IST" finished-at="2019-12-06T16:20:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- catalogLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.High.tests.TC01_InvalidDatailsAddingProduct@57855c9a]" name="tearDown" is-config="true" duration-ms="1015" started-at="2019-12-06T16:20:16 IST" finished-at="2019-12-06T16:20:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.High.tests.TC01_InvalidDatailsAddingProduct -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
